/**
 * Site-wide constants used by metadata, sitemaps, RSS, and JSON-LD. These
 * are deliberately hard-coded (rather than env-var driven) because the
 * canonical URL is a brand-level commitment that rarely changes — and
 * misconfiguring it silently degrades SEO across every page.
 */

export const SITE_URL = "https://makebelieveproductions.com";
export const SITE_NAME = "Make Believe Productions";
export const SITE_TAGLINE = "Magical software for visionaries";
export const SITE_DESCRIPTION =
  "Software consulting for artists and visionaries building consumer products. We translate creative vision into production-quality software.";
export const SITE_AUTHOR = "Justin Paulin";
export const SITE_LOCALE = "en_US";
export const SITE_LANGUAGE = "en";

export const SITE_LOGO_PATH = "/img/modern-treasury-logo.png"; // TODO: replace with a brand logo asset when one exists
export const DEFAULT_OG_IMAGE = "/og/default.png"; // generated by sitemap/build if a default isn't authored

/** Resolve a path against the site URL, returning an absolute URL. */
export function siteUrl(pathname = "/"): string {
  const path = pathname.startsWith("/") ? pathname : `/${pathname}`;
  return `${SITE_URL}${path}`;
}
