/**
 * Build-time script: scans `content/hero/` for source images and writes
 * a corresponding dot-data JSON file for each into `public/data/`, plus a
 * TypeScript manifest module at `src/data/manifest.ts` that the app
 * imports directly (no runtime fetch, no race with the dev server).
 *
 * Idempotent: skips images whose source mtime is older than the existing
 * output, so it's cheap to chain into `dev` and `build`.
 *
 * Usage:
 *   npm run process-images
 *   npm run process-images -- --spacing 10 --force
 */

import fs from "fs";
import path from "path";
import { imageToDots } from "../src/lib/image-to-dots";

const SOURCE_DIR = "content/hero";
const OUTPUT_DIR = "public/data";
const MANIFEST_MODULE_PATH = "src/data/manifest.ts";
const SUPPORTED_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp"]);

const args = process.argv.slice(2);
const getArg = (flag: string, fallback: string) => {
  const i = args.indexOf(flag);
  return i !== -1 && args[i + 1] ? args[i + 1] : fallback;
};
const force = args.includes("--force");

const OPTIONS = {
  gridSpacing: parseInt(getArg("--spacing", "8"), 10),
  canvasWidth: parseInt(getArg("--width", "1920"), 10),
  canvasHeight: parseInt(getArg("--height", "1080"), 10),
  // Threshold of 0 ensures every grid position emits a dot, so dot indices
  // are stable across images and can morph in place without remapping.
  darknessThreshold: 0,
};

interface ManifestEntry {
  source: string;
  output: string;
}

async function main() {
  const sourceDir = path.resolve(process.cwd(), SOURCE_DIR);
  const outputDir = path.resolve(process.cwd(), OUTPUT_DIR);

  if (!fs.existsSync(sourceDir)) {
    console.error(`Source directory not found: ${SOURCE_DIR}`);
    process.exit(1);
  }

  fs.mkdirSync(outputDir, { recursive: true });

  const sourceFiles = fs
    .readdirSync(sourceDir)
    .filter((name) => SUPPORTED_EXTS.has(path.extname(name).toLowerCase()))
    .sort();

  if (sourceFiles.length === 0) {
    console.warn(`No images found in ${SOURCE_DIR}`);
  } else {
    console.log(
      `Grid: ${OPTIONS.canvasWidth}x${OPTIONS.canvasHeight} @ ${OPTIONS.gridSpacing}px spacing`
    );
    console.log(`Found ${sourceFiles.length} image(s) in ${SOURCE_DIR}`);
  }

  const manifest: ManifestEntry[] = [];
  let processed = 0;
  let skipped = 0;

  for (const filename of sourceFiles) {
    const inputPath = path.join(sourceDir, filename);
    const outputName = `${path.basename(filename, path.extname(filename))}.json`;
    const outputPath = path.join(outputDir, outputName);

    manifest.push({ source: filename, output: outputName });

    const inputStat = fs.statSync(inputPath);
    const outputExists = fs.existsSync(outputPath);
    const outputStat = outputExists ? fs.statSync(outputPath) : null;

    if (!force && outputStat && outputStat.mtimeMs >= inputStat.mtimeMs) {
      skipped++;
      console.log(`  skip ${filename} (up to date)`);
      continue;
    }

    process.stdout.write(`  process ${filename}... `);
    const buf = fs.readFileSync(inputPath);
    const result = await imageToDots(buf, OPTIONS);
    fs.writeFileSync(outputPath, JSON.stringify(result));
    processed++;
    const kb = (fs.statSync(outputPath).size / 1024).toFixed(0);
    console.log(`ok  ${result.dots.length.toLocaleString()} dots (${kb} KB)`);
  }

  // Clean up stale outputs that no longer have a source image
  const expectedOutputs = new Set(manifest.map((e) => e.output));
  for (const existing of fs.readdirSync(outputDir)) {
    if (!existing.endsWith(".json")) continue;
    if (!expectedOutputs.has(existing)) {
      fs.unlinkSync(path.join(outputDir, existing));
      console.log(`  remove stale ${existing}`);
    }
  }

  // Emit a TypeScript module the app imports directly. Skipping the
  // network round-trip avoids the iOS Safari "Load failed" failure mode
  // we saw when `manifest.json` was fetched at runtime in dev.
  const manifestModulePath = path.resolve(process.cwd(), MANIFEST_MODULE_PATH);
  fs.mkdirSync(path.dirname(manifestModulePath), { recursive: true });
  const imagesLiteral = manifest
    .map((e) => `  ${JSON.stringify(e.output)},`)
    .join("\n");
  const manifestSource = `// Auto-generated by scripts/process-images.ts. Do not edit by hand.
// Regenerate via \`npm run process-images\` (also runs on dev/build).

export interface HeroManifest {
  generatedAt: string;
  images: readonly string[];
}

export const heroManifest: HeroManifest = {
  generatedAt: ${JSON.stringify(new Date().toISOString())},
  images: [
${imagesLiteral}
  ],
};
`;
  fs.writeFileSync(manifestModulePath, manifestSource);

  console.log(
    `Done. ${processed} processed, ${skipped} skipped, ${manifest.length} in manifest.`
  );
  console.log(`Wrote ${MANIFEST_MODULE_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
