// Auto-generated by scripts/process-content.ts. Do not edit by hand.
// Regenerate via `npm run process-content` (also runs on dev/build).

export interface BlogManifestEntry {
  slug: string;
  /** Folder name under content/blog/ (may include a YYYY-MM-DD- prefix). */
  folder: string;
  title: string;
  /** ISO 8601 date string (frontmatter `date`) */
  date: string;
  description: string;
  author: string;
  tags: readonly string[];
  heroAlt: string;
  /** Absolute URL path (under /public) for the dot-data JSON. */
  dotsPath: string;
  /** 1200x630 OG image path. */
  ogImagePath: string;
  /** 800x800 square thumbnail used by the blog index card. */
  squareImagePath: string;
  readingTimeMinutes: number;
  canonical: string | null;
  draft: boolean;
  /** Mtime of the most-recently-edited post asset (mdx or hero). */
  sourceMtime: string;
}

export interface BlogManifest {
  generatedAt: string;
  posts: readonly BlogManifestEntry[];
}

export const blogManifest: BlogManifest = {
  generatedAt: "2026-04-29T00:03:40.307Z",
  posts: [
  {
    "slug": "hello-world",
    "folder": "2026-04-28-hello-world",
    "title": "Hello, world",
    "date": "2026-04-28T00:00:00.000Z",
    "description": "Notes on a new corner of the site — what we're going to write about, and why.",
    "author": "Justin Paulin",
    "tags": [
      "notes",
      "process"
    ],
    "heroAlt": "Aerial photograph of a coastline",
    "dotsPath": "/data/blog/hello-world.json",
    "ogImagePath": "/og/blog/hello-world.png",
    "squareImagePath": "/og/blog/hello-world.square.png",
    "readingTimeMinutes": 1,
    "canonical": null,
    "draft": false,
    "sourceMtime": "2026-04-28T22:07:19.116Z"
  }
],
};
