// Auto-generated by scripts/process-content.ts. Do not edit by hand.
// Regenerate via `npm run process-content` (also runs on dev/build).

export interface BlogManifestEntry {
  slug: string;
  /** Folder name under content/blog/ (may include a YYYY-MM-DD- prefix). */
  folder: string;
  title: string;
  /** ISO 8601 date string (frontmatter `date`) */
  date: string;
  description: string;
  author: string;
  tags: readonly string[];
  heroAlt: string;
  /** Absolute URL path (under /public) for the dot-data JSON. */
  dotsPath: string;
  /** 1200x630 OG image path. */
  ogImagePath: string;
  /** 800x800 square thumbnail used by the blog index card. */
  squareImagePath: string;
  readingTimeMinutes: number;
  canonical: string | null;
  draft: boolean;
  /** Mtime of the most-recently-edited post asset (mdx or hero). */
  sourceMtime: string;
}

export interface BlogManifest {
  generatedAt: string;
  posts: readonly BlogManifestEntry[];
}

export const blogManifest: BlogManifest = {
  generatedAt: "2026-04-29T18:30:41.435Z",
  posts: [
  {
    "slug": "craft-at-speed",
    "folder": "2026-04-29-craft-at-speed",
    "title": "Craft at Speed",
    "date": "2026-04-29T00:00:00.000Z",
    "description": "Open-sourcing the agent skills we use to keep codebases clean.",
    "author": "Justin Molineaux",
    "tags": [
      "craft",
      "ai",
      "process",
      "open-source"
    ],
    "heroAlt": "Dot image of a craftsperson swinging a hammer, sparks scattering into ribbons of color against a deep blue ground",
    "dotsPath": "/data/blog/craft-at-speed.json",
    "ogImagePath": "/og/blog/craft-at-speed.png",
    "squareImagePath": "/og/blog/craft-at-speed.square.png",
    "readingTimeMinutes": 5,
    "canonical": null,
    "draft": false,
    "sourceMtime": "2026-04-29T18:30:28.760Z"
  }
],
};
